# ubuntu as base image

FROM ubuntu:18.04

# install git
RUN apt-get update && \
    apt-get install -y git

# git clone https://github.com/tsaie79/qubitPack.git
RUN git clone https://github.com/tsaie79/qubitPack.git

